### ISSUE TITLE
Messaging ReviewBot in private crash

### ISSUE THREAD

**Issue by laurentkempe** [martinskuta/ReviewBot#2]
with following message sent

> Sorry, it looks like something went wrong. Error: Cannot perform runtime binding on a null reference

**Comment by glconti** [comment]
@martinskuta said the bot works only in channels, not in 1 to 1 conversations, since it stores/retrieves context info by channel

**Comment by laurentkempe** [comment]
oh ok @glconti

**Comment by martinskuta** [comment]
Yeah, that is known issue :) I will keep it open though. The problem is that the bot stores data per channel, so in private chat, there is no notion of channel, so when it tries to get the channel id from the message the binding crashes (the channel data is dynamic object). 

I will implement something so the bot explains it in the private chat, instead of crashing :)

**Comment by martinskuta** [comment]
Now the bot returns a help response in private chat instead of crashing
